server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由


        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            - After=2021-11-19T21:50:31.134+08:00[Asia/Shanghai] #在这个时间段之后生效
            #- Cookie=username,atguigu
            #- Header=X-Request-Id, \d+
            #- Host=**.atguigu.com
            - Query=username, \d+
          filters:
            #- Hystrix=default
            - name: Hystrix
              args:
                name: fallbackCmdA
                fallbackUri: forward:/fallback

# 全局
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    # 对单独设置Hystrix的commandKey的超时时间
    fallbackCmdA:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

eureka:
  #instance:
    #hostname: localhost
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


